dist: xenial
language: rust

matrix:
  include:
    - rust: beta
      env:
        - CARGO_FLAGS=+beta
        - TOOLCHAIN="--toolchain beta"
      os: linux
    - rust: stable
      env: 
        - CARGO_FLAGS=+stable
        - TOOLCHAIN="--toolchain stable"
      os: linux
    - os: linux
    - os: windows
    - os: osx

install:
- rustup component add $TOOLCHAIN rustfmt clippy

script:
- cargo $CARGO_FLAGS build --all --all-features --verbose
- cargo $CARGO_FLAGS test --all --all-features --verbose
- cargo $CARGO_FLAGS clippy --all -- -Dwarnings
- cargo $CARGO_FLAGS clippy --all --tests -- -Dwarnings
- cargo $CARGO_FLAGS fmt --all -- --check
- cargo $CARGO_FLAGS doc --all --no-deps
