dist: xenial
language: rust

install:
- rustup component add rustfmt clippy

script:
- cargo build --all-features --verbose
- cargo test --all-features --verbose
- cargo clippy -- -Dwarnings
- cargo clippy --tests -- -Dwarnings
- cargo fmt --all -- --check
- cargo doc --no-deps
