dist: xenial
language: rust

os:
  - windows
  - linux

install:
- rustup component add rustfmt clippy

script:
- cargo build --all --all-features --verbose
- cargo test --all --all-features --verbose
- cargo clippy --all -- -Dwarnings
- cargo clippy --all --tests -- -Dwarnings
- cargo fmt --all -- --check
- cargo doc --all --no-deps
