[package]
name = "mockiato"
version = "0.1.0"
authors = [
    "Ruben Schmidmeister <ruben@myelin.ch>",
    "Jeremy Stucki <jeremy@myelin.ch>",
]
edition = "2018"
license = "MIT"

[dependencies]
mockiato_codegen = { path = "../mockiato_codegen" }
