[package]
name = "mockiato_codegen"
version = "0.1.0"
authors = ["Ruben Schmidmeister <ruben.schmidmeister@icloud.com>"]
edition = "2018"
license = "MIT"

[lib]
plugin = true

[dev-dependencies]
compiletest_rs = "0.3.14"
