[package]
name = "mockiato_codegen"
version = "0.1.0"
authors = ["Ruben Schmidmeister <ruben.schmidmeister@icloud.com>"]
edition = "2018"
license = "MIT"

[lib]
plugin = true

[depedencies]
lazy_static = "1.1.0"
